university:
  abbr: ${UNIVERSITY_ABBR}
  name: ${UNIVERSITY_NAME}
  url: ${UNIVERSITY_URL}
  basicAuth:
    login: ${UNIVERSITY_LOGIN}
    password: ${UNIVERSITY_PASSWORD}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

import:
  url: http://api.rvuzov.ru/v2/import/file
  type: json
  token: ${IMPORT_TOKEN}
  report: ${IMPORT_REPORT}
